@startuml
class 图书管理员{
用户名
密码
}
class 读者{
学号
姓名
班级
借书号
已借图书
归还图书
}
class 系统管理员{
用户名
密码
}
class 图书{
ISBN
名称
作者
价格
出版社
库存量
}
class 借还记录{
借书号
借书ISBN
借书时间
归还时间
借书时长
}
class 违规罚款{
违规账户
违规原因
违规时间
罚款金额
}
class 续借图书{
续借账户
续借书籍
续借时间
续借时长
}
class 预定图书{
预定账户
预定图书
预定时间
预定时长
}
class 订单管理{
订单号
订单名称
订单描述
创建时间
}

系统管理员"1"<-- "*"图书管理员:管理
图书管理员"1"<--"*"读者:管理
图书管理员"1"<--"*"图书:管理
图书管理员"1"<--"*"订单管理:管理
图书管理员"1"<--"*"预定图书:预定
图书管理员"1"<--"*"违规罚款:管理
图书管理员"1"<--"*"借还记录:管理
系统管理员"1"<--"*"订单管理:管理

读者"1"--"*"借还记录:查询
读者"1"-"*"续借图书:续借


@enduml
